### ISSUE TITLE
unittest default statedir of ncm-cdispd and ncm-ncd

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-cdispd#36]
so they are equal / different, but as intended.

question: what is the intended default (equal or not).

**Comment by stdweird** [comment]
values are currently only set in the shipped config files.
can we move the defaults to the Application defaults?

**Comment by jouvin** [comment]
March 17 workshop: `cdispd` has this option only to pass it to `ncd`. Should probably be removed or at least its default value should be undefined.

**Comment by jrha** [comment]
It might be useful for some use cases (which should be documented) but the default should be to not pass it to ncm-ncd by default.

**Comment by ned21** [comment]
There are a number of other options (such as cache_root and NoAction) to ncm-cdispd which should normally never be changed. However, collectively they are useful for e.g. running a second instance that downloads a "canary" version of the profile and runs it in NoAction mode. So we should leave these options in the code for now.
