### ISSUE TITLE
configuration changes with non-existing path

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-cdispd#39]
currently, the `changed_CPE` code treats a missing CPE path in the new config *sometimes* as an error and returns nothing has changed. 

i would propose that the check for non-existing paths in the new config is performed first. 

this would introduce possible backwards incompatible behaviour, but would remove any randomness.
currenlty, non-existing CPEs should be very rare hard when the component type is used, but not impossible (eg removing the component package from /software/packages, and running without the `noautoregpkg` is sufficient)

**Comment by jouvin** [comment]
`change_CPE` return value is not a status code but a boolean saying if `ncm-ncd` needs to dispatch this component... `change_CPE` currently considers nothing as an error...
