### ISSUE TITLE
16.10.0-rc1: verbose too verbose!

### ISSUE THREAD

**Issue by jouvin** [quattor/ncm-cdispd#45]
With verbose now being the default logging level, it is necessary to degrade the message ` no new profile found, sleeping` to debug1. Else, the log file is full of this useless message (1 every 2 minutes).

IMO, showstopper for [16.10.0-rc1](https://github.com/quattor/release/issues/266).

**Comment by stdweird** [comment]
it's ofcourse nice to know the daemon is still alive and working well.
how about we only do a verbose log every e.g. 10 iterations?

**Comment by jouvin** [comment]
I don't know how useful it is to have a message saying "I'm still alive"... It's also a pollution of the log file... But if you'd like to go this way, I'd suggest one message every hour at the maximum, not something based on a number of iterations. And it should be one hour without any other event (timer reset when a new profile is detected).
