### ISSUE TITLE
Postinstall script restarts service, which re-runs ncm-ncd part-way through an upgrade.

### ISSUE THREAD

**Issue by jrha** [quattor/ncm-cdispd#50]
`ncm-cdispd` is restarted by the post-install script during an upgrade, at the point at which the restart happens the system is in an inconsistent state, where some packages have not yet been upgraded — cue scary "bad Perl code" warnings.

Here are sanitised logs for [sl6x](https://gist.github.com/jrha/9801ea3bff1fbdaa37ae611661aa9da6) and [sl7x](https://gist.github.com/jrha/dac64f4427dee1601ac4243a892b9d6c) VMs showing the problem.

As mentioned in quattor/release#297.

**Comment by stdweird** [comment]
to be clear: the sl6 logs shows a different issue as the sl7 logs. i knew about the sl6 one, i didn't about the sl7 (or i always assume the sl7 error was the sl6 one).

the sl7 error is a very strange beast (is it reading a partially updated file? how would that even be possible...), but is probably due to systemd handling the restart via ncm-chkconfig as opposed to the rpm postinstall via chkconfig

**Comment by jrha** [comment]
Also to be clear, the system eventually gets updated correctly and works, but it's a confusing mess in the middle and it scares me to think what might happen if something got stuck.

**Comment by stdweird** [comment]
@jrha we deployed 17.3.0 release rpms, and are hit by permament broken `ncm-cdispd`.

**Comment by jrha** [comment]
:fearful:

**Comment by jrha** [comment]
It would be really good to understand what happened, can you tell why `ncm-cdispd` is broken?
It was functioning correctly after the upgrade on the test hosts we used.

**Comment by stdweird** [comment]
can you send me a md5sum of the `/usr/sbin/ncm-cdispd`? and `rpm -qa|grep perl`

**Comment by stdweird** [comment]
@jrha on a sl7/centos7 system

**Comment by stdweird** [comment]
@jrha these are actual code bugs, introduced in https://github.com/quattor/ncm-cdispd/pull/48/commits/56471eb366e0a25293157c24f5bba0409e637fdf

a few things went wrong:
1. it looks like we (at UGent i mean) did not ever test this, opposed to what i claimed. i seem to have never pushed the rpm to the repo...
2. perlcritic doesn't see errors like this (incl the syntax error)
3. our unittests can't load scripts, so another test path that should really capture this didn't catch this

i'm really puzzled how this can have worked at RAL.

anyway, PR coming up. either make a 17.3.1 for this or revoke the rpm from the release

**Comment by jrha** [comment]
The original test VMs have been destroyed, but a recently upgraded VM does indeed have a broken ncm-cdispd. Not sure how I didn't notice. :disappointed: 
I'm going to delete the RPM from the repo to prevent anyone else breaking their systems and issue a 17.3.1.

**Comment by stdweird** [comment]
Fixes are 
* missing `;` to close anon-sub (https://github.com/quattor/ncm-cdispd/pull/52/files#diff-76b4fa87b63e1bc5d0bc50ce36f3234cR379)
* PIDFILE scope in if block (https://github.com/quattor/ncm-cdispd/pull/52/files#diff-76b4fa87b63e1bc5d0bc50ce36f3234cR250)

**Comment by jrha** [comment]
@stdweird was this really *fixed* by your PR?
The postinstall script is still doing confusing things is it not?

**Comment by stdweird** [comment]
@jrha the EL7 things should be gone. what are you still seeing?

**Comment by jrha** [comment]
The issue describes the restart of cdispd by the postinstall script, if that is not problematic then the issue title and description should be updated.

**Comment by stdweird** [comment]
afaik, the restart is not the issue
